language: node_js
services:
  - docker
cache:
  directories:
  - $HOME/.gitbook
install:
  - npm install -g gitbook-cli
script:
  - make build
  - docker run -t -v $(pwd)/_book:/site 18fgsa/html-proofer /site
